import DS from 'ember-data';
import { Model } from 'ember-pouch';

export default Model.extend({
  teamId: DS.attr('string'),
  quarterBackId: DS.attr('string'),
  runningBack1Id: DS.attr('string'),
  runningBack2Id: DS.attr('string'),
  wideReceiver1Id: DS.attr('string'),
  wideReceiver2Id: DS.attr('string'),
  tightEndId: DS.attr('string'),
  flexId: DS.attr('string'),
  kickerId: DS.attr('string'),
  defenseId: DS.attr('string'),
  bench1Id: DS.attr('string'),
  bench2Id: DS.attr('string'),
  bench3Id: DS.attr('string'),
  bench4Id: DS.attr('string'),
  bench5Id: DS.attr('string'),

  quarterback: null,
  runningBack1: null,
  runningBack2: null,
  wideReceiver1: null,
  wideReceiver2: null,
  tightEnd: null,
  flex: null,
  kicker: null,
  defense: null,
  bench1: null,
  bench2: null,
  bench3: null,
  bench4: null,
  bench5: null,
});
